### ISSUE TITLE
Documentation issues?

### ISSUE THREAD

**Issue by smatterchew** [OneIdentity/ansible-authentication-services#22]
First issue:
At this link: https://github.com/OneIdentity/ansible-authentication-services/blob/master/roles/client_config/README.md#usersallow-usersdeny-groupsallow-and-groupsdeny  on the second line down, you list one of the role managed files as "groups.allows".  I think this should be "groups.allow"?

Second issue:
Are "groups.allow" and "groups.deny" even supported by the product?  I am unable to get them to work, even when managing them by hand.

Thank you

**Comment by plgrantOI** [comment]
I would agree that groups.allow and groups.deny should be removed from the documentation. 
The users.allow and users.deny files themselves support group entries directly per the official admin guide. The only other valid file is per-service files documented here.
https://support.oneidentity.com/technical-documents/safeguard-authentication-services/4.2.4/administration-guide/32#TOPIC-1468070

**Comment by llnagy76** [comment]
As of Release v0.1.0 the client_config role no longer supports the modification of groups.allow and groups.deny files.
Thank you very much for raising the issue!
