### ISSUE TITLE
Allow using keytab for joining instead of password

### ISSUE THREAD

**Issue by pboushy** [OneIdentity/ansible-authentication-services#39]
Instead of using username and password, we routinely use username and keytab to join servers to the domain using vastool. We would like to use the keytab to join servers using this ansible collection.

**Comment by llnagy76** [comment]
@pboushy
I have pushed my changes to a new branch:
https://github.com/llnagy76/ansible-authentication-services/tree/allow_using_keytab_for_joining
May I ask you to test it in your environment?
Thank you very much for your help!

**Comment by llnagy76** [comment]
The enhancement has been released in version 0.3.0.
